"""Rebase hiking enhancements onto an untouched Rudy theme, retaining rule semantics."""
import collections
import hashlib
import json
import xml.etree.ElementTree as ET
from pathlib import Path

NS = 'http://mapsforge.org/renderTheme'
ET.register_namespace('', NS)
ET.register_namespace('xsi', 'http://www.w3.org/2001/XMLSchema-instance')


def build_style(upstream, output, policy):
    tree = ET.parse(upstream)
    counts = collections.Counter()
    def walk(node, ancestors):
        tag = node.tag.rsplit('}', 1)[-1]
        rules = ancestors + ([node.attrib] if tag == 'rule' else [])
        if tag in ('line', 'area', 'pathText', 'caption'):
            # Scoped palette transfer, including alpha; never recolor other blue features.
            if any(r.get('k') in ('waterway', 'natural', 'landuse') and
                   set(r.get('v', '').split('|')) & {'river','stream','canal','ditch','drain','riverbank','water','reservoir','basin'} for r in rules):
                for attr in ('stroke', 'fill'):
                    color = node.get(attr, '')
                    for old, new in policy['water_colors'].items():
                        if color.upper().endswith(old):
                            node.set(attr, color[:-6] + new)
                            counts['water_colors'] += 1
                            break
                if tag == 'line' and node.get('stroke', '').upper().endswith(policy['water_colors']['B3DDFF']):
                    node.set('stroke-width', str(round(float(node.get('stroke-width', '0')) * policy['water_width_factor'], 3)))
                    counts['water_lines'] += 1
        if tag == 'line' and any(r.get('k') == 'highway' and
                set(r.get('v', '').split('|')) <= {'path','footway','steps','bridleway'} and r.get('v') for r in rules):
            # Preserve difficulty colors, dash sequences, tunnel and access distinctions.
            if node.get('stroke-width'):
                node.set('stroke-width', str(round(float(node.get('stroke-width')) * policy['trail_width_factor'], 3)))
                counts['trail_lines'] += 1
        if tag == 'symbol' and any((r.get('k') == 'man_made' and r.get('v') == 'survey_point') or
                r.get('k') == 'historic' or (r.get('k') == 'tourism' and
                set(r.get('v', '').split('|')) & {'camp_site','wilderness_hut','alpine_hut'}) for r in rules):
            for attr in ('symbol-width','symbol-height'):
                if node.get(attr):
                    node.set(attr, str(round(float(node.get(attr)) * policy['landmark_size_factor'])))
            counts['landmark_symbols'] += 1
        for child in list(node):
            if child.tag == '{'+NS+'}area' and 'p_attraction.svg' in child.get('src',''):
                node.remove(child)
                counts['attraction_patterns_removed'] += 1
            else:
                walk(child, rules)
    walk(tree.getroot(), [])
    for key in ('water_colors','water_lines','trail_lines','landmark_symbols','attraction_patterns_removed'):
        if not counts[key]:
            raise ValueError('Upstream style structure changed: no matches for ' + key)
    folder = Path(upstream).parent
    for element in tree.iter():
        src = element.get('src', '')
        if src.startswith('file:') and not (folder / src[5:]).is_file():
            raise ValueError('Missing theme asset: ' + src)
    # Keep upstream attribution/license notice in the portable generated theme.
    prefix = Path(upstream).read_text('utf-8').split('<rendertheme', 1)[0]
    credit = '<!-- Mapwalker enhancements based on bochengsiong by poi890poi; CC BY-NC-SA 3.0. Generated by mapwalker.rudy_style. -->\n'
    payload = (prefix + credit).encode('utf-8') + ET.tostring(tree.getroot(), encoding='utf-8')
    Path(output).write_bytes(payload)
    return dict(counts=counts, upstream_sha256=hashlib.sha256(Path(upstream).read_bytes()).hexdigest(),
                output_sha256=hashlib.sha256(payload).hexdigest())


def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--upstream', type=Path, default=Path('styles/rudy/upstream/MOI_OSM.xml'))
    parser.add_argument('--output', type=Path, default=Path('styles/rudy/upstream/bochengsiong.xml'))
    args = parser.parse_args()
    policy = json.loads((Path(__file__).resolve().parents[1] / 'styles/rudy/enhancements.json').read_text())
    result = build_style(args.upstream, args.output, policy)
    args.output.with_suffix('.build.json').write_text(json.dumps(result, indent=2)+'\n')
    print(json.dumps(result, indent=2))


if __name__ == '__main__':
    main()
