"""Render frozen experiment outputs; does not rerun or tune detectors."""
import html,json,sys
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
OUT=ROOT/'evidence/trail-round4';MARK=ROOT/'evidence/detection-round4'
FONT=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',21)
SMALL=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',17)

def main():
    # Four native crops make contour-following mistakes directly inspectable.
    panels=[('','Historical pixels'),('-baseline','Old short chains'),('-connected-135','Long connected chains'),('-osm','Modern OSM context')]
    sheet=Image.new('RGB',(1056,1144),'#f5f3e9');d=ImageDraw.Draw(sheet)
    for i,(suffix,title) in enumerate(panels):
        x=8+(i%2)*528;y=8+(i//2)*572
        d.text((x,y),title,font=FONT,fill='#193c35')
        d.text((x,y+28),'1924 Wulai | red is unverified; cyan is OSM',font=SMALL,fill='#38544a')
        im=Image.open(OUT/f'JM50K_1924_new-wulai{suffix}.png')
        sheet.paste(im.resize((512,512)),(x,y+52))
    sheet.save(OUT/'comparison.png')
    data=json.loads((ROOT/'evidence/detection-round3/review-data.json').read_text('utf8'))
    repeat=json.loads((MARK/'repeat-v1.json').read_text('utf8'))
    examples=[('development','JM50K_1924_new-vertical'),('fresh','JM50K_1924_new-east')]
    mark_sheet=Image.new('RGB',(1048,966),'#f5f3e9');draw=ImageDraw.Draw(mark_sheet)
    for row,(split,sid) in enumerate(examples):
        suite=data[split];scene=next(s for s in suite['scenes'] if s['id']==sid)
        original=Image.open(ROOT/'evidence/detection-round3'/scene['path']).convert('RGB')
        for col,(title,key) in enumerate([('Current detector',None),('Repeated-patch trial','repeat_patch_texture')]):
            im=original.copy();pd=ImageDraw.Draw(im)
            proposals=suite['new_eligible'][sid] if not key else [p for r in repeat[split] if r['scene']==sid for p in r['proposals']]
            from mapwalker.display import priority
            for p in proposals:
                if priority(p)<.74:continue
                pd.rectangle(p['box'],outline='#cf3058' if p['details'].get(key,False) else '#007b63',width=2)
            x=8+col*524;y=8+row*482
            draw.text((x,y),title,font=FONT,fill='#193c35')
            draw.text((x,y+27),'Known label' if row==0 else 'Background false positives remain',font=SMALL,fill='#38544a')
            mark_sheet.paste(im.resize((416,416)),(x,y+52))
    mark_sheet.save(MARK/'comparison.png')
    css='''body{font:17px/1.5 system-ui,sans-serif;margin:auto;padding:22px;max-width:1100px;background:#f5f3e9;color:#193c35}h1,h2{line-height:1.2}a{color:#006b75}img{max-width:100%;height:auto}section{background:white;padding:20px;margin:24px 0;border-radius:14px}button,select{font:inherit;padding:10px;margin:4px;border:1px solid #67877b;border-radius:8px;background:white;color:#193c35}button[aria-pressed=true]{background:#193c35;color:white}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:10px;border-bottom:1px solid #ccc}.scroll{overflow:auto}.note{border-left:5px solid #b87428;padding-left:15px}.zoom{overflow:auto;max-height:85vh}.zoom img.full{max-width:none;width:1024px}small{display:block}'''
    connected=json.loads((OUT/'connected-v1.json').read_text());width=json.loads((OUT/'width-v1.json').read_text())
    countrows=''
    for row in connected:
        counts=[len(r['paths']) for r in row['runs']]
        countrows+=f'<tr><td>{html.escape(row["scene"])}</td>'+''.join(f'<td>{v}</td>' for v in counts)+f'<td>{len(next(r for r in width if r["scene"]==row["scene"])["paths"])}</td></tr>'
    models=json.loads((OUT/'road-model-v1.json').read_text())
    controls=json.loads((OUT/'osm-controls-v1.json').read_text('utf8'))
    crows=''
    for r in controls['runs']:
        for c in r['controls']:
            crows+=f'<tr><td>{r["scene"].split("-wulai")[0]}</td><td>{c["shift_x_px"]:+} px</td><td>{c["samples"]}</td><td>{c["connected_dash_supported_fraction"]:.1%}</td><td>{c["road_supported_fraction"]:.1%}</td></tr>'
    page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mapwalker — trail experiments, round 4</title><style>{css}</style>
<a href="/">← Mapwalker</a><h1>Long trails: what worked, what failed</h1><p>30 September 2026 · Wulai · both historical map series · GTX 1650</p>
<p class="note"><b>Experimental results, not a detector upgrade.</b> Long connected chains still followed contours. The unadapted Swiss historical-road model did not recover reliable Taiwan trails. No new trail candidates from these experiments were added to your map.</p>
<section><h2>Inspect the actual pixels</h2><p>Switch layers at the same location. Red shows unverified image detections; cyan shows modern OSM routes. OSM is context, never historical ground truth.</p>
<label>Historical series <select id="scene"><option value="JM50K_1924_new-wulai">1924 陸地測量部 新版</option><option value="JM50K_1916-wulai">1916 番地地形圖</option></select></label>
<div id="layers"></div><button id="size">View native pixels / fit screen</button><p id="caption"></p><div class="zoom"><img id="map" width="1024" height="1024" alt="Historical map experiment comparison"></div><small>Historical tiles: 中央研究院 GIS · 1024×1024 native mosaics, z16, 16 tiles each. Modern routes: © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors, ODbL</a>. The historical series have local positional differences.</small></section>
<section><h2>Connectivity is necessary, but not sufficient</h2><img src="comparison.png" loading="lazy" alt="Historical pixels, old short chains, long connected chains and modern OSM context"><p>The long-chain experiment chooses the nearest aligned dash at each end, requires mutual connections, at least 8 dashes and 120 pixels of length, and rejects loops. It reduces fragments but still follows broken contours. Darker ink reduces output without solving this. Adding a 3.5-pixel thickness proxy produces no long paths.</p>
<div class="scroll"><table><tr><th>Sample</th><th>Old short chains</th><th>Long chains</th><th>Darker ink only</th><th>Thicker dashes only</th></tr>{countrows}</table></div><p><b>These are output counts, not precision or recall.</b> Fewer lines alone is not an improvement. The connected and thickness variants fail the visual gate.</p></section>
<section><h2>A small pretrained model: fits the GPU, fails to transfer</h2><p>Tested the authors’ ResNet18 attention U-Net from <a href="https://arxiv.org/abs/2410.02250">Probabilistic road classification in historical maps using synthetic data and deep learning</a>. It was trained on Swiss mapping, not these Taiwan series. This was inference only, with the supplied checkpoint and author RGB/255 normalization.</p>
<p>Checkpoint: 61.0 MB. Peak allocated GPU memory: {models['runs'][0]['peak_allocated_mb']:.0f} MiB (reserved {models['runs'][0]['peak_reserved_mb']:.0f} MiB). Nine overlapping 512-pixel crops per mosaic. Timed inference: {models['runs'][0]['seconds']:.2f}s / {models['runs'][1]['seconds']:.2f}s, excluding model loading. At the published 0.5 threshold, 1924 produces no positive pixels; 1916 highlights mostly contour fragments. This is not a usable trail detector here.</p><img src="JM50K_1916-wulai-road-model.png" loading="lazy" alt="Published model highlights contour fragments in red on the 1916 map"><p><a href="https://huggingface.co/DominikM198/ProbRoadClass-DeepLearning">Author weights (CC BY 4.0)</a> · <a href="https://github.com/DominikM198/ProbRoadClass-DeepLearning/tree/09e04bb87a306e46acbf37c0df74ba28628365a1">Pinned author code (MIT)</a></p></section>
<section><h2>OSM: useful context, not permission to invent a route</h2><p>Modern path/footway/track/steps/bridleway geometries were taken from four cached Overpass snapshots. Each route is sampled every 4 pixels, searching up to 40 pixels perpendicular to the route to allow local displacement. The same 939 interior samples are also shifted 150 pixels west and east. No missing geometry is bridged.</p><p>We ask whether a cross-section touches an image candidate. This deliberately permissive check can hit contours. Original OSM alignment has more contacts with the 1924 dash graph than the shifts, but visual review still finds contour errors. The model gives almost identical tiny support on the older map. <b>No route is accepted on this basis.</b></p>
<div class="scroll"><table><tr><th>Series</th><th>OSM shift</th><th>Samples</th><th>Touches dash graph</th><th>Touches model ≥ .5</th></tr>{crows}</table></div><p>OSM tags describe modern conditions; absence of OSM cannot exclude an old trail. At this latitude, 40 pixels is approximately 87 metres and 150 pixels approximately 325 metres. These controls are not a precision test, and the modern geometry is shared across both historical layers.</p></section>
<section><h2>What to improve next</h2><p>The graph starts with isolated connected ink components. Where a real dash touches a contour or text, it can become a larger component and be discarded before path tracing. Requiring a long chain can then lose the remaining real fragments. This is a plausible failure mechanism from the code, not yet a measured explanation for every miss. The next useful experiment is a dense dash likelihood map that preserves evidence at crossings, followed by curved path tracing with explicit penalties for unsupported gaps, width changes and parallel contour bundles.</p><p>Train that likelihood map first on generated curved dashed trails over generated contour fields, including intersections, fading, broken printing, text and vegetation. OSM can prioritize review corridors and propose local alignment hypotheses. Keep image-only search outside OSM corridors. Freeze the candidate before evaluating a new area. This path avoids a dependency on user labeling; any manual traces remain evaluation-only.</p><p>No new holdout was used to claim success: all candidates failed on development material and none is being deployed. These two Wulai mosaics cannot establish Taiwan-wide performance.</p><p><a href="../detection-round4/report.html">Text and symbol clutter experiments →</a></p></section>
<section><h2>Reproducibility</h2><p><a href="contract.md">Predeclared experiment contract</a> · <a href="inputs.json">Historical input hashes</a> · <a href="connected-v1.json">Graph outputs</a> · <a href="width-v1.json">Width outputs</a> · <a href="road-model-v1.json">GPU run</a> · <a href="osm-controls-v1.json">OSM provenance and controls</a> · <a href="osm-trails.geojson">OSM routes</a> · <a href="review.md">Decision record</a></p></section>
<script>const modes=[['','Historical pixels','Unmodified historical map.'],['-baseline','Old detector','Short fragments from the current dash-chain detector.'],['-connected-135','Long chains','Long paths still follow broken contours.'],['-connected-110','Darker ink','Only the ink threshold changed.'],['-width','Thicker dashes','No long paths survive; missed trails are a failure.'],['-road-model','Pretrained model','Pink = probability at least 0.5; unadapted and unreliable here.'],['-osm','Modern OSM','Cyan = modern routes only, not detected historical trails.']];let selected='';const pic=document.getElementById('map');function render(){{pic.src=document.getElementById('scene').value+selected+'.png';document.getElementById('caption').textContent=modes.find(m=>m[0]===selected)[2];document.querySelectorAll('#layers button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===selected)))}}for(const [mode,label] of modes){{const b=document.createElement('button');b.textContent=label;b.dataset.mode=mode;b.onclick=()=>{{selected=mode;render()}};document.getElementById('layers').append(b)}}document.getElementById('scene').onchange=render;document.getElementById('size').onclick=()=>pic.classList.toggle('full');render();</script></html>'''
    (OUT/'report.html').write_text(page,encoding='utf8')
    (MARK/'report.html').write_text(f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mapwalker — mark clutter, round 4</title><style>{css}</style><a href="/">← Mapwalker</a><h1>Text and symbols: clutter experiments</h1><p class="note"><b>No demonstrated improvement in this round.</b> Two automatic repetition checks preserved the known labels but failed to remove the measured false positives. Neither is deployed.</p><section><h2>Image evidence</h2><img src="comparison.png" alt="Before and trial boxes on a known label and a background-only patch"><p>Green boxes are candidates eligible for Top quality before density filtering. The false boxes in the background patch remain. Red would show a proposed demotion; none of these top candidates is demoted.</p></section><section><h2>What was tested</h2><p>First: high-pass patch matching to find repeated textures. Second: compare isolated component shapes so nearby contours do not dominate the match. Both use only map pixels and existing proposals. No place names, user markings, manual readings or reference boxes enter inference.</p><table><tr><th>Frozen suite</th><th>Known marks, before → after</th><th>Background boxes, before → after</th></tr><tr><td>Development</td><td>9/10 → 9/10</td><td>0 → 0</td></tr><tr><td>Round-3 fresh (reused)</td><td>5/5 → 5/5</td><td>5 → 5</td></tr><tr><td>Round-3 final (reused)</td><td>No positive references</td><td>3 → 3</td></tr></table><p>Same result for both variants. One low-priority proposal was flagged by patch matching; none by component matching. All raw candidates were retained. “Fresh” and “final” are the prior suite names, not fresh holdouts for this round. References are sparse evaluation-only examples, not an exhaustive accuracy estimate.</p></section><section><h2>Where the clutter comes from</h2><p>A read-only snapshot of current completed detector jobs contained 300 Top-eligible legacy symbol candidates and 423 Top-eligible character-region candidates. Coverage differs by detector, so those totals are not precision scores. They show why improving only text-region output cannot solve all visible clutter.</p><p>The next mark experiment should test richer synthetic hard negatives—repeated vegetation at variable sizes and contour intersections—alongside a separate small landmark proposal head. Keep unreadable glyphs as findings and recognition optional. Do not lower recall by forcing unknown shapes into a fixed symbol dictionary.</p><p><a href="../trail-round4/report.html">Trail experiments and OSM controls →</a></p></section><section><h2>Evidence files</h2><p><a href="contract.md">Contract</a> · <a href="repeat-v1-summary.json">Patch summary</a> · <a href="repeat-component-v1-summary.json">Component summary</a> · <a href="pipeline-audit.json">Pipeline snapshot</a></p></section></html>''',encoding='utf8')

if __name__=='__main__':main()
