"""Build the reviewable, private multi-evidence experiment report."""
import html
import json
from pathlib import Path
from urllib.parse import urlencode

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'evidence/multi-evidence'
esc=lambda value:html.escape(str(value),quote=True)


def main():
    result=json.loads((OUT/'evaluation.json').read_text('utf-8'))
    rows={r['id']:r for r in json.loads((OUT/'inputs.json').read_text('utf-8'))}
    body=[]
    for sample in result['samples']:
        r=sample['result']
        if r['state']=='unknown':continue
        pid=sample['id'];p=rows[pid]
        link='/#'+urlencode(dict(lat=p['lat'],lon=p['lon'],z=17,source=p['source'],display='all',visibility='all'))
        cards=[]
        for candidate in r['candidates'][:3]:
            f=candidate['feature']['properties'];details=[]
            for e in candidate['evidence']:
                if e['channel']=='name':details.append(f"OCR {e['reading']} ↔ {e['alias']} ({e['reason']})")
                if e['channel']=='elevation':details.append(' / '.join(f"{v['reading_m']} ↔ {v['modern_m']} m" for v in e['comparisons']))
                if e['channel']=='terrain':details.append(f"20 m DTM: {e['elevation_m']} m; {e['below_local_max_m']} m below local high" if e['state']=='available' else f"Terrain {e['state']}")
            cards.append(f'<li><a href="{esc(f["url"])}" target="_blank" rel="noopener">{esc(f["name"] or "Unnamed feature")}</a> · {candidate["distance_m"]} m<br>{esc(" · ".join(details) or "Proximity only")}</li>')
        body.append(f'<article data-state="{esc(r["state"])}"><h2>#{pid} · <bdi>{esc(p["text"])}</bdi></h2><p>{esc(r["state"])} · {esc(p["source"])}</p><a href="{pid}.png"><img src="{pid}.png" alt="Unmodified historical crop for finding {pid}" loading="lazy"></a><ol>{"".join(cards)}</ol><p><a href="{esc(link)}" target="_blank">Map vicinity (all candidates) ↗</a> · <a href="/api/pois/{pid}/supporting-evidence" target="_blank">Live evidence JSON ↗</a></p></article>')
    links=''.join(f'<tr><td>{v["id"]}</td><td>{v["baseline_rank"] or "absent"}</td><td>{v["rank"] or "absent"}</td><td>{esc(v["state"])}</td></tr>' for v in result['links'])
    stages=''.join(f'<tr><td>{esc(name)}</td><td>{v["states"].get("name-supported",0)}</td><td>{v["states"].get("ambiguous",0)}</td><td>{v["states"].get("elevation-compatible",0)}</td><td>{sum(r["rank"]==1 for r in v["links"])}/12</td></tr>' for name,v in result['ablations'].items())
    page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Multi-evidence detection review · Mapwalker</title>
<style>body{{font:17px/1.55 system-ui,sans-serif;background:#f0f2e9;color:#183a34;margin:0}}main{{max-width:1160px;padding:28px;margin:auto}}h1{{font-size:clamp(30px,5vw,48px);line-height:1.15}}a{{color:#165e68}}.lead{{font-size:21px}}.panel,article{{background:white;border:1px solid #c6d4ca;border-radius:12px;padding:22px;margin:20px 0}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr));gap:18px}}article{{margin:0}}article img{{width:100%;height:260px;object-fit:contain;background:#efeee5}}article h2{{margin:0}}li{{margin:12px 0}}table{{border-collapse:collapse;width:100%;font-size:15px}}td,th{{border-bottom:1px solid #d8dfd8;padding:8px;text-align:left}}.scroll{{overflow:auto}}select{{font:inherit;padding:9px;border-radius:7px}}small{{color:#52665f}}.badge{{background:#dcebe4;padding:7px 12px;border-radius:8px;display:inline-block;margin:5px}}pre{{white-space:pre-wrap;overflow-wrap:anywhere}}[hidden]{{display:none}}</style>
<main><p><a href="/">← Mapwalker</a> · Experiment, 2 October 2026</p><h1>Map text + names + terrain</h1><p class="lead">16 review leads from 6,302 frozen detections. Ranked hypotheses are now available in each finding’s inspector.</p>
<span class="badge">5 name-supported</span><span class="badge">3 competing name matches</span><span class="badge">8 height-compatible</span>
<section class="panel"><h2>What changed</h2><p>Raw OCR and existing reading-direction alternatives are compared with nearby OSM names and historical aliases, plus the MOI natural-feature gazetteer. Native 20 m DTM measures relief and elevation at modern coordinates. A 1 km search accommodates displaced labels without snapping them to a summit.</p><p>Names, numeric agreement and proximity remain distinct. Missing evidence means unknown. Saved annotations and OSM links are used only for evaluation. Existing detections, display priorities, coordinates and annotation state are preserved.</p><p><strong>Decision:</strong> land explainable counterpart ranking and this review queue. Defer automatic display promotion: numeric identity, historical units and independent accuracy are not established. Hollow-circle filtering remains rejected; <a href="../hollow-dot/report.html">the legends include meaningful trees and circular landmarks</a>.</p></section>
<section class="panel"><h2>Controlled comparisons</h2><p>Distance-only ordering puts the saved OSM counterpart first in 1/12 cases. Automatic text/type evidence puts it first in 4/12 and in the first three in 8/12, versus 4/12. None ranks lower. These 12 associations represent only 9 distinct OSM objects; they are selected development examples, not 12 independent trials or a detection recall estimate.</p><div class="scroll"><table><thead><tr><th>Stage</th><th>Name leads</th><th>Ambiguous</th><th>Height leads</th><th>Saved link first</th></tr></thead><tbody>{stages}</tbody></table></div><p>The gazetteer adds 3 name leads (拳頭母山 and two detections of 阿玉山). Terrain provides measured elevation/relief, but adds no demonstrated ranking improvement in this sample. OSM and the gazetteer may share source material and are never counted as independent votes.</p><p>Of 103 saved classifications, both name-supported/ambiguous cases are POIs; all 46 Noise and 34 Other cases remain undecided. This small set has no annotated symbol POI positives and cannot establish safety of symbol suppression.</p><details><summary>Per-association ranks</summary><div class="scroll"><table><thead><tr><th>POI</th><th>Distance only</th><th>Evidence rank</th><th>Identity state</th></tr></thead><tbody>{links}</tbody></table></div></details><p>Pure comparison timing, including first-use terrain initialization: median {result['timing']['median_ms']:.3f} ms, p95 {result['timing']['p95_ms']:.2f} ms, maximum {result['timing']['max_ms']:.0f} ms. This excludes source-file acquisition, gazetteer lookup and HTTP/rendering. Most detections have little or no cached OSM context.</p></section>
<section class="panel"><h2>Visual check and rejected experiment</h2><p>All 16 surfaced crops were inspected after the matching rules were fixed. Fourteen were not previously annotated; several overlap known locations or duplicate the same mark, so this is a visual spot check, not a blind geographic holdout. The crops show actual names or numbers, but that alone does not verify which modern object they identify. The first digit in #8028 is uncertain and illustrates why OCR/height agreement must not become automatic confirmation.</p><p>A separate four-rotation crop OCR trial on the 103 annotated marks recovered several contour numbers but did not recover the important unread peak/elevation labels reliably. It also produced partial and wrong numbers. Rejected for production; its readings do not feed this comparison.</p><p><a href="region-readings.json">Rejected OCR trial</a> · <a href="visual-sample.json">Crop provenance</a> · <a href="hypotheses.jpg">All 16 crops</a></p></section>
<section class="panel"><h2>Source provenance</h2><p><a href="https://data.gov.tw/dataset/40456">MOI natural-feature gazetteer</a>: 2,844 rows, historical/alternate names where present. It does not provide a reliable peak/col subclass for every record. <a href="https://data.gov.tw/dataset/176927">2025 mainland DTM</a>: 20 × 20 m native pixels, projected Transverse Mercator CRS read from the raster, NoData excluded. No 10 m data acquired. Both use Government Data Open License 1.0.</p><p>© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>, ODbL 1.0. Forty-one cached query snapshots were frozen; coverage is incomplete. Gazetteer/terrain gaps are not historical negatives.</p><p><a href="provenance.json">Hashes and source URLs</a> · <a href="contract.json">Experiment contract</a> · <a href="evaluation.json">Raw evaluation</a> · <a href="inputs.json">Frozen automatic inputs</a> · <a href="evaluation-labels.json">Separate evaluation labels</a></p></section>
<h2>Review the leads</h2><p>These cards include numeric findings currently hidden by display thinning. Their stored detection priority has not changed. Distances are from the historical label to modern geometry.</p><label>Show <select id="filter"><option value="all">All 16 leads</option><option value="name-supported">Name-supported</option><option value="ambiguous">Competing names</option><option value="elevation-compatible">Height-compatible</option></select></label><div class="grid">{''.join(body)}</div></main>
<script>document.getElementById('filter').onchange=e=>document.querySelectorAll('article').forEach(c=>c.hidden=e.target.value!=='all'&&c.dataset.state!==e.target.value);</script></html>'''
    (OUT/'report.html').write_text(page,'utf-8')


if __name__=='__main__':main()
